version: '3'

services:
  db:
    container_name: rest-template.db
    image: postgres
    networks:
      - local
    ports:
      - 5432:5432
    env_file:
      - './.env'

networks:
  local:
    driver: bridge